public enum InstructionType
{
    ADDITION,
    ASSIGN,
    CALL,
    COMPARE,
    GET_CONSTANT,
    GET_OBJECT_POINTER,
    GET_SELF_POINTER,
    GET_VARIABLE,
    JUMP,
    LABEL,
    MOVE,
    MULTIPLICATION,
    PASS_PARAMETER,
    RETURN,
    SUBTRACT
}