@echo off
del Unit_*.asm
del Unit_*.obj
del Unit_*.dll
del Unit_*.exe
del v.*.asm
del v.*.obj
del v.*.dll
del v.exe
del Instructions-*.asm
del Instructions-*.bin
del Instructions-*.disassembly
del Instructions-*.disassembly.reduced
del Instructions-Expected.o
del coverage.cobertura.xml