#!/bin/bash
dotnet build Vivid.csproj -c Units
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD
echo "Optimization is disabled"
echo ""
./bin/Units/net5.0/Vivid
echo ""
echo "Optimization is enabled"
echo ""
./bin/Units/net5.0/Vivid -O

rm libUnit_*